const colors = {
  light: {
    text: "#1A1A2E",
    tint: "#1B3A6B",
    background: "#F5F7FA",
    foreground: "#1A1A2E",
    card: "#FFFFFF",
    cardForeground: "#1A1A2E",
    primary: "#1B3A6B",
    primaryForeground: "#FFFFFF",
    secondary: "#7C5CBF",
    secondaryForeground: "#FFFFFF",
    muted: "#E8EDF5",
    mutedForeground: "#8B9BB4",
    accent: "#27AE60",
    accentForeground: "#FFFFFF",
    destructive: "#E74C3C",
    destructiveForeground: "#FFFFFF",
    border: "#D9E1EE",
    input: "#D9E1EE",
    purple: "#7C5CBF",
    purpleLight: "#F0EBF9",
    blueDeep: "#1B3A6B",
    blueLight: "#EBF0F9",
    greenSafe: "#27AE60",
    greenLight: "#E8F7EE",
    warning: "#F39C12",
    warningLight: "#FEF5E4",
    surface: "#FFFFFF",
    surfaceAlt: "#F0F2F7",
  },
  dark: {
    text: "#E8EDF5",
    tint: "#4A90D9",
    background: "#0D1B33",
    foreground: "#E8EDF5",
    card: "#162040",
    cardForeground: "#E8EDF5",
    primary: "#4A90D9",
    primaryForeground: "#FFFFFF",
    secondary: "#9B7FD4",
    secondaryForeground: "#FFFFFF",
    muted: "#1A2A4A",
    mutedForeground: "#6B7FA8",
    accent: "#2ECC71",
    accentForeground: "#FFFFFF",
    destructive: "#E74C3C",
    destructiveForeground: "#FFFFFF",
    border: "#1E3055",
    input: "#1E3055",
    purple: "#9B7FD4",
    purpleLight: "#1E1435",
    blueDeep: "#1B3A6B",
    blueLight: "#162040",
    greenSafe: "#2ECC71",
    greenLight: "#0A2E1A",
    warning: "#F39C12",
    warningLight: "#2E2208",
    surface: "#162040",
    surfaceAlt: "#1A2A4A",
  },
  radius: 16,
};

export default colors;
