uploads = []
outputs = []

[[generated]]
id = "Df0EBqff0vtDU3Njtj0DG"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "kHBtXZH2LG_4HIeUZPOix"
uri = "file://artifacts/mobile/assets/images/hero.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5xu04Vg4q_yIbNOS3Ar5N"
uri = "file://artifacts/mobile/assets/images/safety_hero.png"
type = "image"
title = "generated_image"

[[generated]]
id = "HXuVLNFpSxA-XbnxEM-I9"
uri = "file://artifacts/mobile/assets/images/bridge_guide.png"
type = "image"
title = "generated_image"

[[generated]]
id = "fL4Tx-Y7TyAtwnHHU_dkl"
uri = "file://artifacts/mybestie-explainer/public/images/bg-grid.png"
type = "image"
title = "dark neon grid background"

[[generated]]
id = "PgBkUj2DC6ucOFqDQcg8t"
uri = "file://artifacts/mybestie-explainer/public/images/avatar1.png"
type = "image"
title = "abstract avatar 1"

[[generated]]
id = "Llb_KHfRkeyQhAG4xP_1G"
uri = "file://artifacts/mybestie-explainer/public/images/avatar2.png"
type = "image"
title = "abstract avatar 2"

[[generated]]
id = "U3KTQFEe411imSp3I8Olw"
uri = "file://artifacts/mybestie-explainer/public/images/badge.png"
type = "image"
title = "badge icon"
